### PR TITLE
Update Python installation to current pybind11 example

### PR DESCRIPTION
**Pull request by bfut**
adapted from: https://github.com/pybind/python_example

pip installation successfully tests on macos, linux, and windows, python >=3.6 and pypy==3.8, see https://github.com/bfut/tinyobj_ci_install/actions/runs/3184177372

I have no experience with cibuildwheel and cannot check it.

### CODE REVIEW

**Comment by syoyo** [comment]
Good! Unfortunately I found PR still does not work well with pip < 20.3

Could you please add `"pip>=20.3"` to `pyproject.toml` and how https://github.com/bfut/tinyobj_ci_install/  goes? 

```
$ python -m pip --version
pip 20.2.4 from /home/syoyo/miniconda3/lib/python3.8/site-packages/pip (python 3.8)
$ python -m pip install . 
Processing /home/syoyo/work/tinyobjloader-org/python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: tinyobjloader
  Building wheel for tinyobjloader (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/syoyo/miniconda3/bin/python /home/syoyo/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp2fmcd7gr
       cwd: /tmp/pip-req-build-rw98w2oi
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'tinyobjloader' extension
  creating build/temp.linux-x86_64-cpython-38
  gcc -pthread -B /home/syoyo/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DVERSION_INFO=2.0.0rc9 -I/tmp/pip-build-env-k1mg4y_z/overlay/lib/python3.8/site-packages/pybind11/include -I/home/syoyo/miniconda3/include/python3.8 -c bindings.cc -o build/temp.linux-x86_64-cpython-38/bindings.o -fvisibility=hidden -g0 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  bindings.cc:11:10: fatal error: ../tiny_obj_loader.h: No such file or directory
     11 | #include "../tiny_obj_loader.h"
        |          ^~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for tinyobjloader
Failed to build tinyobjloader
ERROR: Could not build wheels for tinyobjloader which use PEP 517 and cannot be installed directly
```

**Comment by bfut** [comment]
After testing, I found that it has to be pip>=21.3. This PR is now updated accordingly.

For the record, this result is bestseen here: https://github.com/bfut/tinyobj_ci_install/actions/runs/3189591809 NB: The current pip version 22.2.2 is apparently not available for Python 3.6, so that test failed as well. However, pip 21.3 *is* available for Python 3.6, so the latter can still be supported.)

**Comment by syoyo** [comment]
@bfut Thanks! Let me give some time to investigate the PR. Probably I also need to rewrite CI python binding build script. Then some CI build failure(e.g. https://github.com/tinyobjloader/tinyobjloader/pull/342/checks?check_run_id=8721374450) will also be fixed.

**Comment by bfut** [comment]
Thanks. I investigated further and looked into *cibuildwheel* as well. The solution for the mysteriously missing header error is to place ``setup.py`` in the project's root folder. In the repo structure as-is, setup.py is one level below ``tiny_obj_loader.h``

There are two possible solutions for this:
1) Move ``setup.py`` and ``pyproject.toml`` to root. (canonical python folder structure).
cibuildwheel now works out of the box without messy copy/move operations. pip install now also works for pip<21.3

2) Leave the folder structure as it is now. Before building python, copy ``tiny_obj_loader.h`` and ``mapbox/earcut.hpp`` into the python folder. This is being done in azure-pipelines.yml when building wheels.
Great for CI, but bad for local builds with pip, because you end up with multiple copies of ``tiny_obj_loader.h``

If you go for option 1, I'll happily change this PR.

**Comment by syoyo** [comment]
@bfut I'd like to go with 1. i.e. put python build scripts in the root of the repo. The reason of having python related stuff in `python` folder is to protesting tinyobjloader is a C++ project and Python binding is optional, but recent Python build system doesn't like such a folder layout...

**Comment by bfut** [comment]
Split the PR into two commits: First file operations, then code changes. pyproject.toml and setup.py now keep their commit history. (It's my first real PR.)

**Comment by syoyo** [comment]
@bfut Thanks! I will update CI build script e.g. https://github.com/tinyobjloader/tinyobjloader/blob/master/azure-pipelines.yml to align to this new Python file layout. Let me give some more time...

**Comment by syoyo** [comment]
@bfut I did some fix to make Azure CI build green on top of your PR! Thank your for the contribution! Closing via https://github.com/tinyobjloader/tinyobjloader/pull/345
